title: snimu's blog
author: Sebastian
description: Thoughts on LLMs, AI, and language model training
url: "https://snimu.github.io"
timezone: Europe/Berlin

remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed

# Beautiful Jekyll specific settings
navbar-links:
  Posts: "/"

social-network-links:
  github: snimu

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true